/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClubeRouteImport } from './routes/clube'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as ClubeIndexRouteImport } from './routes/clube.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RestauranteIdRouteImport } from './routes/restaurante.$id'
import { Route as PerfilNotificacoesRouteImport } from './routes/perfil.notificacoes'
import { Route as PerfilFavoritosRouteImport } from './routes/perfil.favoritos'
import { Route as PerfilDadosRouteImport } from './routes/perfil.dados'
import { Route as PerfilAjudaRouteImport } from './routes/perfil.ajuda'
import { Route as OwnerReservasRouteImport } from './routes/owner.reservas'
import { Route as OwnerExperienciasRouteImport } from './routes/owner.experiencias'
import { Route as OwnerCuponsRouteImport } from './routes/owner.cupons'
import { Route as OwnerConfiguracoesRouteImport } from './routes/owner.configuracoes'
import { Route as ClubeIdRouteImport } from './routes/clube.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminRestaurantesRouteImport } from './routes/admin.restaurantes'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminProprietariosRouteImport } from './routes/admin.proprietarios'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeRoute = ClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const ClubeIndexRoute = ClubeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RestauranteIdRoute = RestauranteIdRouteImport.update({
  id: '/restaurante/$id',
  path: '/restaurante/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilNotificacoesRoute = PerfilNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilFavoritosRoute = PerfilFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilDadosRoute = PerfilDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilAjudaRoute = PerfilAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => PerfilRoute,
} as any)
const OwnerReservasRoute = OwnerReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerExperienciasRoute = OwnerExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCuponsRoute = OwnerCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerConfiguracoesRoute = OwnerConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => OwnerRoute,
} as any)
const ClubeIdRoute = ClubeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClubeRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantesRoute = AdminRestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProprietariosRoute = AdminProprietariosRouteImport.update({
  id: '/proprietarios',
  path: '/proprietarios',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clube': typeof ClubeRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRouteWithChildren
  '/perfil': typeof PerfilRouteWithChildren
  '/recompensas': typeof RecompensasRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/proprietarios': typeof AdminProprietariosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/restaurantes': typeof AdminRestaurantesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clube/$id': typeof ClubeIdRoute
  '/owner/configuracoes': typeof OwnerConfiguracoesRoute
  '/owner/cupons': typeof OwnerCuponsRoute
  '/owner/experiencias': typeof OwnerExperienciasRoute
  '/owner/reservas': typeof OwnerReservasRoute
  '/perfil/ajuda': typeof PerfilAjudaRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/restaurante/$id': typeof RestauranteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/clube/': typeof ClubeIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/recompensas': typeof RecompensasRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/proprietarios': typeof AdminProprietariosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/restaurantes': typeof AdminRestaurantesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clube/$id': typeof ClubeIdRoute
  '/owner/configuracoes': typeof OwnerConfiguracoesRoute
  '/owner/cupons': typeof OwnerCuponsRoute
  '/owner/experiencias': typeof OwnerExperienciasRoute
  '/owner/reservas': typeof OwnerReservasRoute
  '/perfil/ajuda': typeof PerfilAjudaRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/restaurante/$id': typeof RestauranteIdRoute
  '/admin': typeof AdminIndexRoute
  '/clube': typeof ClubeIndexRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clube': typeof ClubeRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRouteWithChildren
  '/perfil': typeof PerfilRouteWithChildren
  '/recompensas': typeof RecompensasRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/proprietarios': typeof AdminProprietariosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/restaurantes': typeof AdminRestaurantesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clube/$id': typeof ClubeIdRoute
  '/owner/configuracoes': typeof OwnerConfiguracoesRoute
  '/owner/cupons': typeof OwnerCuponsRoute
  '/owner/experiencias': typeof OwnerExperienciasRoute
  '/owner/reservas': typeof OwnerReservasRoute
  '/perfil/ajuda': typeof PerfilAjudaRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/restaurante/$id': typeof RestauranteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/clube/': typeof ClubeIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clube'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/owner'
    | '/perfil'
    | '/recompensas'
    | '/reservas'
    | '/reset-password'
    | '/signup'
    | '/admin/proprietarios'
    | '/admin/reservas'
    | '/admin/restaurantes'
    | '/auth/callback'
    | '/clube/$id'
    | '/owner/configuracoes'
    | '/owner/cupons'
    | '/owner/experiencias'
    | '/owner/reservas'
    | '/perfil/ajuda'
    | '/perfil/dados'
    | '/perfil/favoritos'
    | '/perfil/notificacoes'
    | '/restaurante/$id'
    | '/admin/'
    | '/clube/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/recompensas'
    | '/reservas'
    | '/reset-password'
    | '/signup'
    | '/admin/proprietarios'
    | '/admin/reservas'
    | '/admin/restaurantes'
    | '/auth/callback'
    | '/clube/$id'
    | '/owner/configuracoes'
    | '/owner/cupons'
    | '/owner/experiencias'
    | '/owner/reservas'
    | '/perfil/ajuda'
    | '/perfil/dados'
    | '/perfil/favoritos'
    | '/perfil/notificacoes'
    | '/restaurante/$id'
    | '/admin'
    | '/clube'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clube'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/owner'
    | '/perfil'
    | '/recompensas'
    | '/reservas'
    | '/reset-password'
    | '/signup'
    | '/admin/proprietarios'
    | '/admin/reservas'
    | '/admin/restaurantes'
    | '/auth/callback'
    | '/clube/$id'
    | '/owner/configuracoes'
    | '/owner/cupons'
    | '/owner/experiencias'
    | '/owner/reservas'
    | '/perfil/ajuda'
    | '/perfil/dados'
    | '/perfil/favoritos'
    | '/perfil/notificacoes'
    | '/restaurante/$id'
    | '/admin/'
    | '/clube/'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClubeRoute: typeof ClubeRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PerfilRoute: typeof PerfilRouteWithChildren
  RecompensasRoute: typeof RecompensasRoute
  ReservasRoute: typeof ReservasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RestauranteIdRoute: typeof RestauranteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube': {
      id: '/clube'
      path: '/clube'
      fullPath: '/clube'
      preLoaderRoute: typeof ClubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/clube/': {
      id: '/clube/'
      path: '/'
      fullPath: '/clube/'
      preLoaderRoute: typeof ClubeIndexRouteImport
      parentRoute: typeof ClubeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/restaurante/$id': {
      id: '/restaurante/$id'
      path: '/restaurante/$id'
      fullPath: '/restaurante/$id'
      preLoaderRoute: typeof RestauranteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/notificacoes': {
      id: '/perfil/notificacoes'
      path: '/notificacoes'
      fullPath: '/perfil/notificacoes'
      preLoaderRoute: typeof PerfilNotificacoesRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/favoritos': {
      id: '/perfil/favoritos'
      path: '/favoritos'
      fullPath: '/perfil/favoritos'
      preLoaderRoute: typeof PerfilFavoritosRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/dados': {
      id: '/perfil/dados'
      path: '/dados'
      fullPath: '/perfil/dados'
      preLoaderRoute: typeof PerfilDadosRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/ajuda': {
      id: '/perfil/ajuda'
      path: '/ajuda'
      fullPath: '/perfil/ajuda'
      preLoaderRoute: typeof PerfilAjudaRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/owner/reservas': {
      id: '/owner/reservas'
      path: '/reservas'
      fullPath: '/owner/reservas'
      preLoaderRoute: typeof OwnerReservasRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/experiencias': {
      id: '/owner/experiencias'
      path: '/experiencias'
      fullPath: '/owner/experiencias'
      preLoaderRoute: typeof OwnerExperienciasRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/cupons': {
      id: '/owner/cupons'
      path: '/cupons'
      fullPath: '/owner/cupons'
      preLoaderRoute: typeof OwnerCuponsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/configuracoes': {
      id: '/owner/configuracoes'
      path: '/configuracoes'
      fullPath: '/owner/configuracoes'
      preLoaderRoute: typeof OwnerConfiguracoesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/clube/$id': {
      id: '/clube/$id'
      path: '/$id'
      fullPath: '/clube/$id'
      preLoaderRoute: typeof ClubeIdRouteImport
      parentRoute: typeof ClubeRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurantes': {
      id: '/admin/restaurantes'
      path: '/restaurantes'
      fullPath: '/admin/restaurantes'
      preLoaderRoute: typeof AdminRestaurantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proprietarios': {
      id: '/admin/proprietarios'
      path: '/proprietarios'
      fullPath: '/admin/proprietarios'
      preLoaderRoute: typeof AdminProprietariosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProprietariosRoute: typeof AdminProprietariosRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminRestaurantesRoute: typeof AdminRestaurantesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProprietariosRoute: AdminProprietariosRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminRestaurantesRoute: AdminRestaurantesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClubeRouteChildren {
  ClubeIdRoute: typeof ClubeIdRoute
  ClubeIndexRoute: typeof ClubeIndexRoute
}

const ClubeRouteChildren: ClubeRouteChildren = {
  ClubeIdRoute: ClubeIdRoute,
  ClubeIndexRoute: ClubeIndexRoute,
}

const ClubeRouteWithChildren = ClubeRoute._addFileChildren(ClubeRouteChildren)

interface OwnerRouteChildren {
  OwnerConfiguracoesRoute: typeof OwnerConfiguracoesRoute
  OwnerCuponsRoute: typeof OwnerCuponsRoute
  OwnerExperienciasRoute: typeof OwnerExperienciasRoute
  OwnerReservasRoute: typeof OwnerReservasRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerConfiguracoesRoute: OwnerConfiguracoesRoute,
  OwnerCuponsRoute: OwnerCuponsRoute,
  OwnerExperienciasRoute: OwnerExperienciasRoute,
  OwnerReservasRoute: OwnerReservasRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface PerfilRouteChildren {
  PerfilAjudaRoute: typeof PerfilAjudaRoute
  PerfilDadosRoute: typeof PerfilDadosRoute
  PerfilFavoritosRoute: typeof PerfilFavoritosRoute
  PerfilNotificacoesRoute: typeof PerfilNotificacoesRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilAjudaRoute: PerfilAjudaRoute,
  PerfilDadosRoute: PerfilDadosRoute,
  PerfilFavoritosRoute: PerfilFavoritosRoute,
  PerfilNotificacoesRoute: PerfilNotificacoesRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClubeRoute: ClubeRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PerfilRoute: PerfilRouteWithChildren,
  RecompensasRoute: RecompensasRoute,
  ReservasRoute: ReservasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RestauranteIdRoute: RestauranteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
