/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestauranteIdRouteImport } from './routes/restaurante.$id'
import { Route as PerfilNotificacoesRouteImport } from './routes/perfil.notificacoes'
import { Route as PerfilFavoritosRouteImport } from './routes/perfil.favoritos'
import { Route as PerfilDadosRouteImport } from './routes/perfil.dados'
import { Route as PerfilAjudaRouteImport } from './routes/perfil.ajuda'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranteIdRoute = RestauranteIdRouteImport.update({
  id: '/restaurante/$id',
  path: '/restaurante/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilNotificacoesRoute = PerfilNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilFavoritosRoute = PerfilFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilDadosRoute = PerfilDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilAjudaRoute = PerfilAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => PerfilRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/perfil/ajuda': typeof PerfilAjudaRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/restaurante/$id': typeof RestauranteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/perfil/ajuda': typeof PerfilAjudaRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/restaurante/$id': typeof RestauranteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/perfil/ajuda': typeof PerfilAjudaRoute
  '/perfil/dados': typeof PerfilDadosRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/restaurante/$id': typeof RestauranteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/reservas'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/perfil/ajuda'
    | '/perfil/dados'
    | '/perfil/favoritos'
    | '/perfil/notificacoes'
    | '/restaurante/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/reservas'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/perfil/ajuda'
    | '/perfil/dados'
    | '/perfil/favoritos'
    | '/perfil/notificacoes'
    | '/restaurante/$id'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/reservas'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/perfil/ajuda'
    | '/perfil/dados'
    | '/perfil/favoritos'
    | '/perfil/notificacoes'
    | '/restaurante/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  ReservasRoute: typeof ReservasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RestauranteIdRoute: typeof RestauranteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurante/$id': {
      id: '/restaurante/$id'
      path: '/restaurante/$id'
      fullPath: '/restaurante/$id'
      preLoaderRoute: typeof RestauranteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/notificacoes': {
      id: '/perfil/notificacoes'
      path: '/notificacoes'
      fullPath: '/perfil/notificacoes'
      preLoaderRoute: typeof PerfilNotificacoesRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/favoritos': {
      id: '/perfil/favoritos'
      path: '/favoritos'
      fullPath: '/perfil/favoritos'
      preLoaderRoute: typeof PerfilFavoritosRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/dados': {
      id: '/perfil/dados'
      path: '/dados'
      fullPath: '/perfil/dados'
      preLoaderRoute: typeof PerfilDadosRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/ajuda': {
      id: '/perfil/ajuda'
      path: '/ajuda'
      fullPath: '/perfil/ajuda'
      preLoaderRoute: typeof PerfilAjudaRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PerfilRouteChildren {
  PerfilAjudaRoute: typeof PerfilAjudaRoute
  PerfilDadosRoute: typeof PerfilDadosRoute
  PerfilFavoritosRoute: typeof PerfilFavoritosRoute
  PerfilNotificacoesRoute: typeof PerfilNotificacoesRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilAjudaRoute: PerfilAjudaRoute,
  PerfilDadosRoute: PerfilDadosRoute,
  PerfilFavoritosRoute: PerfilFavoritosRoute,
  PerfilNotificacoesRoute: PerfilNotificacoesRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRouteWithChildren,
  ReservasRoute: ReservasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RestauranteIdRoute: RestauranteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
